[package]
name = "hello_rust"
version = "0.0.0"
edition = "2021"

[dependencies]
jsonrpsee = "0.24.7"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"

[[bin]]
name = "hello_rust"
path = "bin/hello_rust.rs"
